export const languages = [
  { code: "zh-CN", flag: "🇨🇳", label: "简体中文" },
  { code: "zh-TW", flag: "🇨🇳", label: "繁體中文" },
  { code: "en", flag: "🇺🇸", label: "English" },
  { code: "ko", flag: "🇰🇷", label: "한국어" },
  { code: "ja", flag: "🇯🇵", label: "日本語" },
  { code: "fr", flag: "🇫🇷", label: "Français" },
  { code: "ru", flag: "🇷🇺", label: "Русский" },
  { code: "de", flag: "🇩🇪", label: "Deutsch" },
  { code: "id", flag: "🇮🇩", label: "Bahasa Indonesia" },
  { code: "tl", flag: "🇵🇭", label: "Tagalog" },
  { code: "sq", flag: "🇦🇱", label: "Shqip" },
  { code: "tr", flag: "🇹🇷", label: "Türkçe" },
  { code: "my", flag: "🇲🇲", label: "မြန်မာဘာသာ" },
  { code: "th", flag: "🇹🇭", label: "ไทย" },
  { code: "vi", flag: "🇻🇳", label: "Tiếng Việt" },
  { code: "pl", flag: "🇵🇱", label: "Polski" },
  { code: "pt", flag: "🇵🇹", label: "Português" },
];
