/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIProviderConfig: typeof import('./components/chat/AIProviderConfig.vue')['default']
    Button: typeof import('./components/ui/Button.vue')['default']
    ChatPanel: typeof import('./components/chat/ChatPanel.vue')['default']
    CodeBlock: typeof import('./components/chat/CodeBlock.vue')['default']
    ConfirmDialog: typeof import('./components/ui/ConfirmDialog.vue')['default']
    copy: typeof import('./components/ui/Radio copy.vue')['default']
    Dialog: typeof import('./components/ui/Dialog.vue')['default']
    Dropdown: typeof import('./components/ui/Dropdown.vue')['default']
    FileCreateDialog: typeof import('./components/files/FileCreateDialog.vue')['default']
    FileManager: typeof import('./components/files/FileManager.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Input: typeof import('./components/ui/Input.vue')['default']
    MessageBlocks: typeof import('./components/chat/MessageBlocks.vue')['default']
    Radio: typeof import('./components/ui/Radio.vue')['default']
    Select: typeof import('./components/ui/Select.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    Test: typeof import('./components/Test.vue')['default']
    ThoughtBlock: typeof import('./components/chat/ThoughtBlock.vue')['default']
    Toast: typeof import('./components/ui/Toast.vue')['default']
    TreeFileExplorerEnhanced: typeof import('./components/TreeFileExplorerEnhanced.vue')['default']
    VueTreeList: typeof import('./components/ui/tree/VueTreeList.vue')['default']
  }
}
